[package]
name = "mapiproxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
argsplitter = "0.4.0"
mio = { version = "0.8.10", features = [ "net", "os-ext", "os-poll" ] }
slab = "0.4.9"
thiserror = "1.0.56"


# mio:
# + log
# - net
# - os-ext
# - os-poll
