# Config for the 'cargo release' command.
# This can be installed with `cargo install cargo-release`.
# Documentation: https://github.com/crate-ci/cargo-release/blob/master/docs/reference.md

push = true

pre-release-hook = [ "cargo", "run", "--example", "x", "--", "checkreadme" ]
pre-release-commit-message = "Release {{crate_name}} version {{version}}"
tag = true
tag-message = "Release {{crate_name}} {{version}}"

# do not publish to crates.io, also see publish = false at the top
publish = false

[[pre-release-replacements]]
file = "CHANGELOG.md"
search = "## mapiproxy NEXTVERSION - .*"
exactly = 1
replace = "## mapiproxy NEXTVERSION - YYYY-MM-DD\n\n\n## mapiproxy {{version}} - {{date}}"

