

name: Build, Test and Clippy
on:
  push:
    branch:
env:
  CARGO_TERM_COLOR: always
jobs:

  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: check out code
        uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: cargo test
        run: cargo test

      - name: cargo clippy
        run: cargo clippy
